name: buf-pull-request
on: pull_request
jobs:
  validate-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install and setup buf (default latest version)
      - uses: bufbuild/buf-setup-action@v0.3.1
      # Lint protocol buffers
      - uses: bufbuild/buf-lint-action@v0.3.0
      # Detect breaking changes against your protocol buffers
      - uses: bufbuild/buf-breaking-action@v0.4.0
        with:
          # The 'main' branch of the GitHub repository that defines the module
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main"
